export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_ERROR = "FETCH_INGREDIENTS_ERROR";
export const PURCHASE_BURGAR_SUCCESS = "PURCHASE_BURGAR_SUCCESS";
export const PURCHASE_BURGAR_ERROR = "PURCHASE_BURGAR_ERROR";
export const PURCHASE_BURGAR_START = 'PURCHASE_BURGAR_START';
