export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_ERROR = "FETCH_INGREDIENTS_ERROR";
export const PURCHASE_BURGAR_SUCCESS = "PURCHASE_BURGAR_SUCCESS";
export const PURCHASE_BURGAR_ERROR = "PURCHASE_BURGAR_ERROR";
export const PURCHASE_BURGAR_START = 'PURCHASE_BURGAR_START';
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_SUCCESSE';
